const express = require('express');
const cors = require('cors');
const app = express();
const routes = require('./routes/routes');
const cookieParser = require('cookie-parser');
app.use(cors());
app.use(express.json());
app.use(cookieParser());
app.use(routes);
module.exports = app;
